language: java

env:
    global:
        # full path to Saxon jar
        - SAXON_JAR=~/.ant/lib/saxon9he.jar
        - SAXON_VERSION=9.9.0-2

before_script:
    # install Saxon
    - curl -fsSL --create-dirs --retry 5 -o ${SAXON_JAR} http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}.jar

# If Travis CI does not detect Maven or Gradle files it runs Ant: ant test (https://docs.travis-ci.com/user/languages/java/)