dist: precise
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-lxml python3-lxml
    - npm install -g jsonlint
script:
    - ./meta_tests.sh python2 testrules.py
    - ./meta_tests.sh python3 testrules.py
    - jsonlint -q rulesets/standard.json
