dist: precise
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-lxml python3-lxml
    - npm install -g jsonlint
language: python
python:
  - 2.7
  - 3.6
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
script:
    - ./meta_tests.sh python2 testrules.py
    - ./meta_tests.sh python3 testrules.py
    - jsonlint -q rulesets/standard.json
