before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq php5-cli
install: "sudo pip install -r requirements.txt"
script:
 - ./meta_tests.sh python testrules.py
 - ./meta_tests.sh php testrules.php
