language: python
python:
    - "2.7"
    - "3.5"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-lxml python3-lxml
install:
    - pip install jsonschema
    - pip install -r requirements.txt
script:
    - python -m jsonschema -i rulesets/standard.json schema.json
    - ./meta_tests.sh python testrules.py
