dist: precise
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq php5-cli python-lxml python3-lxml
script:
    - ./meta_tests.sh python2 testrules.py
    - ./meta_tests.sh python3 testrules.py
    - ./meta_tests.sh php testrules.php

